stages:
  - name: Build hello-world
#    when:
#      branch: main
#      event: [ push, pull_request ]
    steps:
      - runScriptConfig:
          image: golang:1.16
          shellScript:  |-
            go build -o gin-hello
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: gin-hello:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml