stages:
- name: Build hello-world
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: go build -o gin-hello
  when:
    branch:
      include:
      - main
    event:
      include:
      - push
      - pull_request
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: gin-hello:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 127.0.0.1:34633
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
